# Generated by Django 4.0.4 on 2022-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroitFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_droit_foncier', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_localite', models.CharField(max_length=50)),
                ('nom_localite', models.CharField(max_length=50)),
                ('long_localite', models.FloatField()),
                ('lat_localite', models.FloatField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_acquereur', models.CharField(max_length=50)),
                ('prenom_acquereur', models.CharField(max_length=100)),
                ('date_naiss_acquereur', models.DateField(blank=True, null=True)),
                ('nationa_acquereur', models.CharField(max_length=20)),
                ('tel_acquereur', models.CharField(max_length=10)),
                ('email_acquereur', models.EmailField(max_length=254)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
