# Generated by Django 4.0.4 on 2022-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquereur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_acquereur', models.CharField(max_length=50)),
                ('prenom_acquereur', models.CharField(max_length=100)),
                ('date_naiss_acquereur', models.DateField(blank=True, null=True)),
                ('nationa_acquereur', models.CharField(max_length=20)),
                ('tel_acquereur', models.CharField(max_length=10)),
                ('email_acquereur', models.EmailField(max_length=254)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cite', models.CharField(max_length=50)),
                ('nom_cite', models.CharField(max_length=50)),
                ('date_add', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('date_delete', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_infrast', models.CharField(max_length=50)),
                ('nom_infrast', models.CharField(max_length=50)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_logement', models.CharField(max_length=50)),
                ('libele_logement', models.CharField(max_length=50)),
                ('cout_logement', models.IntegerField()),
                ('date_crea_logement', models.DateField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_site', models.CharField(max_length=50)),
                ('libele_site', models.CharField(max_length=50)),
                ('superfici_site', models.FloatField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_typ_logement', models.CharField(max_length=50)),
                ('libele_typ_logement', models.CharField(max_length=50)),
                ('cout_typ_logement', models.IntegerField()),
                ('date_crea_typ_logement', models.DateField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_delete', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
